spring:
  datasource:
    url: jdbc:mysql://localhost/logistics?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=CTT
    username: root
    password: root
    druid:
      initial-size: 0
      max-active: 8
      min-idle: 0
      time-between-eviction-runs-millis: 60000
      time-between-connect-error-millis: 500
      min-evictable-idle-time-millis: 1800000
      max-evictable-idle-time-millis: 25200000
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
  redis:
    redisson:
      config: classpath:redisson.yml
  cloud:
    circuit:
      breaker:
        enabled: true
    loadbalancer:
      retry:
        enabled: true
feign:
  hystrix:
    enabled: true
  config:
    default:
      connect-timeout: 10000
      read-timeout: 10000
ribbon:
  read-timeout: 60000
  connect-timeout: 60000
hystrix:
  share-security-context: true
  command:
    default:
      circuit-breaker:
        sleep-window-in-milliseconds: 100000
        force-closed: true
      execution:
        isolation:
          thread:
            timeout-in-milliseconds: 600000
dubbo:
  scan:
    base-packages: org.macula.cloud.logistics
  protocol:
    name: dubbo
    port: -1
  registry:
    address: spring-cloud://localhost
  cloud:
    subscribed-services: macula-samples-logistics-gbss