export default function ({poNo}) {
  return {
    autoQuery: true,
    selection: false,
    paging: false,
    transport: {
      read: {
        url: `order/v1/orders/find_one/${poNo}`,
        method: 'get',
      },
    },

    fields: [
      {name: 'poNo', label: '销售单号', readOnly: true},
      {name: 'poProcessCode', label: '订货流程代码', readOnly: true},
      {name: 'poType', label: '销售单类型', readOnly: true},
      {name: 'poPeriod', label: '销售月份', readOnly: true},
      {name: 'poDate', label: '销售日期', readOnly: true},
      {name: 'poStoreNo', label: '销售店铺', readOnly: true},
      {name: 'poBranchNo', label: '销售分公司', readOnly: true},
      {name: 'poRegionNo', label: '销售大区代号', readOnly: true},
      {name: 'poStatus', label: '销售单据状态', readOnly: true},
      {name: 'orderDealerNo', label: '购货人卡号', readOnly: true},
      {name: 'orderDealerName', label: '购货人姓名', readOnly: true},
      {name: 'orderType', label: '购货类型', readOnly: true},
      {name: 'refPoNo', label: '参考源订货单号', readOnly: true},
      {name: 'refPoPeriod', label: '参考源订货单月份', readOnly: true},
      {name: 'refPoDate', label: '参考源订货单日期', readOnly: true},
      {name: 'totalSaleAmt', label: '整单订货总金额', readOnly: true},
      {name: 'totalSaleProductAmt', label: '整单产品金额', readOnly: true},
      {name: 'totalSaleNonProductAmt', label: '整单非产品金额', readOnly: true},
      {name: 'totalSaleDiscountAmt', label: '整单销售折让', readOnly: true},
      {name: 'totalSaleCouponAmt', label: '整单使用优惠券', readOnly: true},

      {name: 'totalSaleNetAmt', label: '整单订货净金额', readOnly: true},
      {name: 'totalTransportAmt', label: '订单实际运费', readOnly: true},
      {name: 'totalCalcPoint', label: '计分合计总点数', readOnly: true},
      {name: 'totalCalcDiscountPoint', label: '计分合计折扣点数', readOnly: true},
      {name: 'totalCalcRebate', label: '计分合计总优差', readOnly: true},
      {name: 'poEntryClass', label: '销售办理来源', readOnly: true},
      {name: 'poEntryDealerNo', label: '销售办代办人', readOnly: true},
      {name: 'poEntryTime', label: '销售单据输入时间', readOnly: true},

      {name: 'poEntryBy', label: '销售单据输入用户', readOnly: true},
      {name: 'poEntryMemo', label: '销售单据输入备注', readOnly: true},
      {name: 'poAppNo', label: '销售订货申请单号', readOnly: true},
      {name: 'poLclNo', label: '销售辅单申请单号', readOnly: true},
      {name: 'poGroupNo', label: '团购单号', readOnly: true},
      {name: 'refSelectedNo', label: '参考单据号', readOnly: true},
      {name: 'poPromFlag', label: '销售促销标示', readOnly: true},
      {name: 'poWholePromCode', label: '整单促销代码', readOnly: true},
      {name: 'poPriceGroupType', label: '定价价格组', readOnly: true},
      {name: 'poPriceAttr', label: '定价属性', readOnly: true},
      {name: 'poReturnRestrictFlag', label: '退货约束标志', readOnly: true},
      {name: 'paymentTotalAmt', label: '支付金额', readOnly: true},

      {name: 'paymentStatus', label: '付款状态', readOnly: true},
      {name: 'paymentTime', label: '付款完成时间', readOnly: true},
      {name: 'paymentDocNo', label: '支付文件序号', readOnly: true},
      {name: 'paymentMemo', label: '支付备注', readOnly: true},
      {name: 'sapPostingFlag', label: 'SAP记账标志', readOnly: true},
      {name: 'sapPostingDate', label: 'SAP记账日期', readOnly: true},
      {name: 'sapPostingDocNo', label: '销售订单号', readOnly: true},
      {name: 'comments', label: '备注', readOnly: true},
      {name: 'lastModifiedDate', label: '最后更新时间', readOnly: true},
      {name: 'lastModifiedBy', label: '最后更新人', readOnly: true},
      {name: 'poOweNo', label: '记欠申请号', readOnly: true},
      {name: 'orderDealerBranchNo', label: '购货人对应的分公司', readOnly: true},
      {name: 'orderDesc', label: '订单摘要', readOnly: true},
      {name: 'companyNo', label: '所属公司编码', readOnly: true},
      {name: 'profitCenterNo', label: '利润中心编号', readOnly: true},
      {name: 'orderCustomerNo', label: '销售顾客号', readOnly: true},
      {name: 'totalWeight', label: '订单总重量', readOnly: true},
      {name: 'totalCalcRebateDs', label: '计分合计直销产品优差', readOnly: true},
      {name: 'totalVatAmt', label: '订单增值税总金额', readOnly: true},
      {name: 'totalConsumTaxAmt', label: '订单消费税总金额', readOnly: true},

      {name: 'totalCompreTaxAmt', label: '订单综合税总金额', readOnly: true},
      {name: 'totalRebateDisAmt', label: '总优差折让金额', readOnly: true},
      {name: 'totalTransportCouponAmt', label: '运费优惠金额', readOnly: true},
      {name: 'poEntryStoreNo', label: '销售代办店铺', readOnly: true},

    ],

  };
}
