image: registry.javalabs.top/tools/cibase:0.9.1

stages:
   - build
   - release

build:
   stage: build
   script:
   - mvn clean package -Dmaven.test.skip=true
   
release:
   stage: release
   script:
   - mvn clean package -Dmaven.test.skip=true
   - cd macula-samples-logistics-api
   # - mvn dockerfile:build dockerfile:push
   # - cd ../macula-samples-logistics-schedule
   # - mvn dockerfile:build dockerfile:push
   #- cd ../macula-samples-logistics-gbss
  # - mvn dockerfile:build dockerfile:push
   - cd ../macula-samples-logistics-admin
   - mvn dockerfile:build dockerfile:push
   # - cd ../macula-samples-logistics-client
   # - mvn dockerfile:build dockerfile:push
   only:
    - master
    - /^release-.*$/
    - /^hotfix-.*$/
    
.auto_devops: &auto_devops |
  http_status_code=`curl -o .auto_devops.sh -s -m 10 --connect-timeout 10 -w %{http_code} "${CHOERODON_URL}/devops/ci?token=${Token}&type=microservice"`
  if [ "$http_status_code" != "200" ]; then
    cat .auto_devops.sh
    exit 1
  fi
  source .auto_devops.sh

before_script:
  - *auto_devops