eureka:
  client:
    serviceUrl:
      defaultZone: http://macula:macula2019@10.87.132.22:31678/eureka
macula:
  cloud:
    security:
      public-urls: /**
spring:
  datasource:
    url: jdbc:mysql://10.87.140.74/db_stock_dev?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=CTT
    username: dbu_stock_dev
    password: ENC(dY5QQRmtBb3XtR8WNcHF3AWcX7ORGiN1)
  redis:
    host: 10.87.140.81
    port: 6381
    password: ENC(wmDUCcbaaXZ/9IOyjzZQSRdSoAW0cP67rVmfyd55SI+LlXLndxcYsw==)
    database: 3
security:
  oauth2:
    client:
      client-id: client
      client-secret: secret
      access-token-uri: https://scc-api-dev.ebestpet.com/oauth/oauth/token
      user-authorization-uri: https://scc-api-dev.ebestpet.com/oauth/oauth/authorize
    resource:
      token-info-uri: https://scc-api-dev.ebestpet.com/oauth/oauth/check_token
      user-info-uri: https://scc-api-dev.ebestpet.com/oauth/api/user