macula:
   cloud:
# oauth2
      security:
         oauth2_login: true
         public-urls: /**
         jwt-key: choerodon
      cainiao:
         appKey: "348295"
         url: "https://link.cainiao.com/gateway/link.do"
         providerId: "746ef6ea271c4aecf69e6ed458964f9c"
         secretKey: "2sf48559Wp2eI86757P1h7DFsICE54Hs"
         version: 20190509001

spring:
   datasource:
      url: jdbc:mysql://172.20.72.137/logistics?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=CTT
      username: root
      password: root
   jpa:
      hibernate:
         ddl-auto: update
   redis:
      hosts: 172.20.72.137:6379
      host: 172.20.72.137
      password: macula@^cloud$
      database: 1

security:
   oauth2:
      client:
         client-id: client
         client-secret: secret
         access-token-uri: https://api.javalabs.top/oauth/oauth/token
         user-authorization-uri: https://api.javalabs.top/oauth/oauth/authorize
      resource:
         token-info-uri: https://api.javalabs.top/oauth/oauth/check_token
         user-info-uri: https://api.javalabs.top/oauth/api/user