# Spring Settings
spring:
   datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      druid:
         initial-size: 0
         max-active: 100
         min-idle: 0
         time-between-eviction-runs-millis: 60000
         time-between-connect-error-millis: 500
         min-evictable-idle-time-millis: 1800000
         max-evictable-idle-time-millis: 25200000
   jpa:
      database: MYSQL
      show-sql: true
      open-in-view: false
   cache:
      type: GENERIC
   servlet:
      multipart:
         max-file-size: 10MB
         max-request-size: 10MB
   mvc:
      static-path-pattern: /**
   resources:
      static-locations: classpath:/static,classpath:/public,classpath:/resources,classpath:/META-INF/resources,file:/dist

# Choerodon Settings
choerodon:
   saga:
      consumer:
         enabled: true # 启动消费端
   schedule:
      consumer:
         enabled: true # 启用任务调度消费端
   resource:
      jwt:
         ignore: /public/**, /favicon.ico

# J2Cache Settings
j2cache:
   open-spring-cache: true
   allow-null-values: false
   cache-clean-mode: passive
   redis-client: jedis
   broadcast: net.oschina.j2cache.cache.support.redis.SpringRedisPubSubPolicy
   L1:
      provider_class: caffeine
   L2:
      provider_class: net.oschina.j2cache.cache.support.redis.SpringRedisProvider
      config_section: spring.redis
caffeine:
   region:
      default: 1000, 1h
      session: 10000, 4h
      users: 1000, 10s