# DataSource Config
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: root
    password: test

  h2:
    console:
      enabled: true

wechat:
  cp:
    corpId: ww1a4cae50e89aef2f
    appConfigs:
      - agentId: 1000038
        secret: Z3ePCbZlVLOr1_GVN3xILaIRYn6O5fxFdwLwWjRkF34
        token: ORM1aii3wBxY52
        aesKey: O3pzG9fU7RjdwdLKfhZ42Hr5Xn9GjOMGHC1HwS99n6D
              
# Logger Config
logging:
  level:
    # root: debug
    org.springframework.web: info
    org.macula.samples.weixin.enterprise: trace
    me.chanjar.weixin: info
