macula:
   cloud:
# oauth2
      security:
         oauth2_login: true
         public-urls: /**
         jwt-key: choerodon
      cainiao:
         appKey: "348295"
         url: "https://link.cainiao.com/gateway/link.do"
         providerId: "746ef6ea271c4aecf69e6ed458964f9c"
         secretKey: "2sf48559Wp2eI86757P1h7DFsICE54Hs"
         publish-version: 20190509001
         version: 18Q4
      logistics:
         initial-effective-date: 2020-09-01 16:30:00
         initial-inactive-date: 2100-01-01 00:00:00

spring:
   datasource:
      url: jdbc:mysql://10.87.140.74/db_logistics_dev?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=CTT
      username: dbu_logistics_dev
      password: abc_123
   redis:
      hosts: 10.87.140.81:6381
      host: 10.87.140.81
      port: 6381
      password: redis%%sccdev321
      database: 1

security:
   oauth2:
      client:
         client-id: client
         client-secret: secret
         access-token-uri: https://api.javalabs.top/oauth/oauth/token
         user-authorization-uri: https://api.javalabs.top/oauth/oauth/authorize
      resource:
         token-info-uri: https://api.javalabs.top/oauth/oauth/check_token
         user-info-uri: https://api.javalabs.top/oauth/api/user